#!/usr/bin/env python3

from glob import glob
import os

HEAD_SIZES_KQ = [40, 64, 72, 80, 96, 112, 128, 192, 256, 320, 512, 576]

# DKQ -> DV override for asymmetric head dims.
HEAD_SIZES_V_OVERRIDE = {576: 512, 320: 256, 192: 128}

TYPES_KV = ["GGML_TYPE_F16", "GGML_TYPE_Q4_0", "GGML_TYPE_Q4_1", "GGML_TYPE_Q5_0", "GGML_TYPE_Q5_1", "GGML_TYPE_Q8_0", "GGML_TYPE_BF16"]

# Additional Turbo pairs supported by the generic vector fallback. These use
# the wider D=512 declaration set and are intentionally not a full Cartesian
# product of every Turbo representation.
TYPES_KV_TURBO = [
    ("GGML_TYPE_Q8_0",       "GGML_TYPE_TURBO2_0"),
    ("GGML_TYPE_Q8_0",       "GGML_TYPE_TURBO3_0"),
    ("GGML_TYPE_Q8_0",       "GGML_TYPE_TURBO4_0"),
    ("GGML_TYPE_TURBO2_0",   "GGML_TYPE_Q8_0"),
    ("GGML_TYPE_TURBO2_0",   "GGML_TYPE_TURBO2_0"),
    ("GGML_TYPE_TURBO2_0",   "GGML_TYPE_TURBO3_0"),
    ("GGML_TYPE_TURBO2_TCQ", "GGML_TYPE_TURBO2_TCQ"),
    ("GGML_TYPE_TURBO2_TCQ", "GGML_TYPE_TURBO3_TCQ"),
    ("GGML_TYPE_TURBO3_0",   "GGML_TYPE_Q8_0"),
    ("GGML_TYPE_TURBO3_0",   "GGML_TYPE_TURBO2_0"),
    ("GGML_TYPE_TURBO3_0",   "GGML_TYPE_TURBO3_0"),
    ("GGML_TYPE_TURBO3_0",   "GGML_TYPE_TURBO4_0"),
    ("GGML_TYPE_TURBO3_TCQ", "GGML_TYPE_TURBO2_TCQ"),
    ("GGML_TYPE_TURBO3_TCQ", "GGML_TYPE_TURBO3_TCQ"),
    ("GGML_TYPE_TURBO4_0",   "GGML_TYPE_Q8_0"),
    ("GGML_TYPE_TURBO4_0",   "GGML_TYPE_TURBO3_0"),
    ("GGML_TYPE_TURBO4_0",   "GGML_TYPE_TURBO4_0"),
]

SOURCE_FATTN_TILE = """// This file has been autogenerated by generate_cu_files.py, do not edit manually.

#include "../fattn-tile.cuh"

DECL_FATTN_TILE_CASE({head_size_kq}, {head_size_v});
"""

SOURCE_FATTN_VEC = """// This file has been autogenerated by generate_cu_files.py, do not edit manually.

#include "../fattn-vec.cuh"

DECL_FATTN_VEC_CASE( 64, {type_k}, {type_v});
DECL_FATTN_VEC_CASE(128, {type_k}, {type_v});
DECL_FATTN_VEC_CASE(256, {type_k}, {type_v});
"""

SOURCE_FATTN_VEC_TURBO = """#include "../fattn-vec.cuh"
DECL_FATTN_VEC_CASE( 64, {type_k}, {type_v});
DECL_FATTN_VEC_CASE(128, {type_k}, {type_v});
DECL_FATTN_VEC_CASE(256, {type_k}, {type_v});
DECL_FATTN_VEC_CASE(512, {type_k}, {type_v});
"""

SOURCE_FATTN_MMA_START = """// This file has been autogenerated by generate_cu_files.py, do not edit manually.

#include "../fattn-mma-f16.cuh"

"""

SOURCE_FATTN_MMA_CASE = "DECL_FATTN_MMA_F16_CASE({head_size_kq}, {head_size_v}, {ncols1}, {ncols2});\n"

SOURCE_FATTN_MMA_CASE_VKV = "DECL_FATTN_MMA_F16_CASE_VKV({head_size_kq}, {head_size_v}, {ncols1}, {ncols2}, true);\n"

TYPES_MMQ = [
    "GGML_TYPE_Q1_0",
    "GGML_TYPE_Q2_0",
    "GGML_TYPE_Q2_0_G128",
    "GGML_TYPE_Q4_0", "GGML_TYPE_Q4_1", "GGML_TYPE_Q5_0", "GGML_TYPE_Q5_1", "GGML_TYPE_Q8_0",
    "GGML_TYPE_Q2_K", "GGML_TYPE_Q3_K", "GGML_TYPE_Q4_K", "GGML_TYPE_Q5_K", "GGML_TYPE_Q6_K",
    "GGML_TYPE_IQ2_XXS", "GGML_TYPE_IQ2_XS", "GGML_TYPE_IQ2_S", "GGML_TYPE_IQ3_XXS", "GGML_TYPE_IQ3_S",
    "GGML_TYPE_IQ1_S", "GGML_TYPE_IQ4_NL", "GGML_TYPE_IQ4_XS", "GGML_TYPE_MXFP4", "GGML_TYPE_NVFP4"
]

SOURCE_MMQ = """// This file has been autogenerated by generate_cu_files.py, do not edit manually.

#include "../mmq.cuh"

DECL_MMQ_CASE({type});
"""

SOURCE_MMF = """// This file has been autogenerated by generate_cu_files.py, do not edit manually.

#include "../mmf.cuh"

DECL_MMF_CASE({type});
"""

# Turbo MMA fused decode instances. Each entry is:
# (filename stem, K type, V type, supported (DKQ, DV) pairs).
#
# Symmetric codecs support the common D=128 geometry and Qwen's D=256 geometry.
# Asymmetric codecs are used by Qwen VBR transitions and only support D=256.
TURBO_VARIANTS = [
    ("fattn-mma-turbo",                       "GGML_TYPE_TURBO4_0",   "GGML_TYPE_TURBO4_0",   [(128, 128), (256, 256)]),
    ("fattn-mma-turbo-turbo8_0",              "GGML_TYPE_TURBO8_0",   "GGML_TYPE_TURBO8_0",   [(128, 128), (256, 256)]),
    ("fattn-mma-turbo-turbo3_0",              "GGML_TYPE_TURBO3_0",   "GGML_TYPE_TURBO3_0",   [(128, 128), (256, 256)]),
    ("fattn-mma-turbo-turbo2_0",              "GGML_TYPE_TURBO2_0",   "GGML_TYPE_TURBO2_0",   [(128, 128), (256, 256)]),
    ("fattn-mma-turbo-turbo3_tcq",            "GGML_TYPE_TURBO3_TCQ", "GGML_TYPE_TURBO3_TCQ", [(128, 128), (256, 256)]),
    ("fattn-mma-turbo-turbo2_tcq",            "GGML_TYPE_TURBO2_TCQ", "GGML_TYPE_TURBO2_TCQ", [(128, 128), (256, 256)]),
    ("fattn-mma-turbo-turbo1_tcq",            "GGML_TYPE_TURBO1_TCQ", "GGML_TYPE_TURBO1_TCQ", [(128, 128), (256, 256)]),
    ("fattn-mma-turbo-turbo8k_turbo4v",       "GGML_TYPE_TURBO8_0",   "GGML_TYPE_TURBO4_0",   [(256, 256)]),
    ("fattn-mma-turbo-turbo4k_turbo8v",       "GGML_TYPE_TURBO4_0",   "GGML_TYPE_TURBO8_0",   [(256, 256)]),
    ("fattn-mma-turbo-turbo4k_turbo3tcqv",    "GGML_TYPE_TURBO4_0",   "GGML_TYPE_TURBO3_TCQ", [(256, 256)]),
    ("fattn-mma-turbo-turbo3tcqk_turbo4v",    "GGML_TYPE_TURBO3_TCQ", "GGML_TYPE_TURBO4_0",   [(256, 256)]),
    ("fattn-mma-turbo-turbo3tcqk_turbo2tcqv", "GGML_TYPE_TURBO3_TCQ", "GGML_TYPE_TURBO2_TCQ", [(256, 256)]),
    ("fattn-mma-turbo-turbo2tcqk_turbo3tcqv", "GGML_TYPE_TURBO2_TCQ", "GGML_TYPE_TURBO3_TCQ", [(256, 256)]),
    ("fattn-mma-turbo-turbo2tcqk_turbo1tcqv", "GGML_TYPE_TURBO2_TCQ", "GGML_TYPE_TURBO1_TCQ", [(256, 256)]),
    ("fattn-mma-turbo-turbo1tcqk_turbo2tcqv", "GGML_TYPE_TURBO1_TCQ", "GGML_TYPE_TURBO2_TCQ", [(256, 256)]),
    ("fattn-mma-turbo-turbo8k_f16v",          "GGML_TYPE_TURBO8_0",   "GGML_TYPE_F16",        [(256, 256)]),
    ("fattn-mma-turbo-f16k_turbo8v",          "GGML_TYPE_F16",        "GGML_TYPE_TURBO8_0",   [(256, 256)]),
]

# The fused path handles at most four query tokens. NVIDIA can use an 8-column
# tile; RDNA starts at 16 columns and needs the 32-column/GQA-8 case for 3-4
# queries. Wider shapes only served the slower, default-off fused-prefill probe.
TURBO_DECODE_SHAPES = [
    (8, 1), (4, 2), (2, 4), (1, 8),
    (16, 1), (8, 2), (4, 4), (2, 8),
    (4, 8),
]

SOURCE_FATTN_MMA_TURBO_START = """{comment}

#include "../fattn-mma-f16.cuh"
#include "../fattn-mma-turbo.cuh"

"""

SOURCE_FATTN_MMA_TURBO_CASE = "DECL_FATTN_MMA_TURBO_CASE({dkq}, {dv}, {ncols1}, {ncols2}, {type_k}, {type_v});\n"


def get_type_name(long_quant_name):
    return long_quant_name.replace("GGML_TYPE_", "", 1)


def get_short_name(long_quant_name):
    return get_type_name(long_quant_name).lower()


def get_turbo_comment(stem, type_k, type_v):
    if stem == "fattn-mma-turbo":
        return "// This file has been autogenerated by generate_cu_files.py, do not edit manually."
    if type_k == type_v:
        return f"// autogenerated turbo fused MMA instance for {get_type_name(type_k)}"
    if type_k == "GGML_TYPE_F16" or type_v == "GGML_TYPE_F16":
        return (f"// autogenerated turbo fused MMA instance for asymmetric {type_k} K / {type_v} V\n"
                "// (f16<->t8 VBR entry band: closes the materialize penalty during the f16->t8 degrade)")
    suffix = "q6 sweet spot" if type_k == "GGML_TYPE_TURBO8_0" and type_v == "GGML_TYPE_TURBO4_0" \
        else "dynamic VBR adjacent-tier pair"
    return (f"// autogenerated turbo fused MMA instance for asymmetric "
            f"{get_type_name(type_k)} K / {get_type_name(type_v)} V ({suffix})")


for filename in glob("*.cu"):
    os.remove(filename)

for head_size_kq in HEAD_SIZES_KQ:
    head_size_v = HEAD_SIZES_V_OVERRIDE.get(head_size_kq, head_size_kq)
    with open(f"fattn-tile-instance-dkq{head_size_kq}-dv{head_size_v}.cu", "w") as f:
        f.write(SOURCE_FATTN_TILE.format(head_size_kq=head_size_kq, head_size_v=head_size_v))

for type_k in TYPES_KV:
    for type_v in TYPES_KV:
        with open(f"fattn-vec-instance-{get_short_name(type_k)}-{get_short_name(type_v)}.cu", "w") as f:
            f.write(SOURCE_FATTN_VEC.format(type_k=type_k, type_v=type_v))
            if type_k == type_v and type_k in ("GGML_TYPE_F16", "GGML_TYPE_Q8_0"):
                f.write(f"DECL_FATTN_VEC_CASE(512, {type_k}, {type_v});\n")

for type_k, type_v in TYPES_KV_TURBO:
    with open(f"fattn-vec-instance-{get_short_name(type_k)}-{get_short_name(type_v)}.cu", "w") as f:
        f.write(SOURCE_FATTN_VEC_TURBO.format(type_k=type_k, type_v=type_v))

for ncols in [8, 16, 32, 64]:
    for ncols2 in [1, 2, 4, 8, 16, 32]:
        if ncols2 > ncols:
            continue
        ncols1 = ncols // ncols2
        with open(f"fattn-mma-f16-instance-ncols1_{ncols1}-ncols2_{ncols2}.cu", "w") as f:
            f.write(SOURCE_FATTN_MMA_START)

            for head_size_kq in HEAD_SIZES_KQ:
                if head_size_kq == 40:
                    continue
                if head_size_kq == 72:
                    continue
                # Skip compilation of unused ncols2 values for niche head sizes:
                if head_size_kq == 192 and ncols2 not in (8, 16): # MiMo-V2.5
                    continue
                if head_size_kq == 320 and ncols2 != 32: # Mistral Small 4
                    continue
                if head_size_kq == 512 and ncols2 not in (2, 4, 8): # Gemma 4 (+ MTP)
                    continue
                if head_size_kq == 576 and ncols2 not in (4, 16, 32): # Deepseek, GLM 4.7 Flash
                    continue
                if head_size_kq not in (192, 320, 576) and ncols2 in (16, 32):
                    continue
                head_size_v = HEAD_SIZES_V_OVERRIDE.get(head_size_kq, head_size_kq)
                f.write(SOURCE_FATTN_MMA_CASE.format(ncols1=ncols1, ncols2=ncols2, head_size_kq=head_size_kq, head_size_v=head_size_v))

# DSV4 (head size 512, K-only attention) uses GQA 16 and therefore ncols2 = 8.
for ncols1, ncols2 in [(1, 8), (2, 8), (4, 8), (8, 8)]:
    with open(f"fattn-mma-f16-instance-vkv-ncols1_{ncols1}-ncols2_{ncols2}.cu", "w") as f:
        f.write(SOURCE_FATTN_MMA_START)
        f.write(SOURCE_FATTN_MMA_CASE_VKV.format(head_size_kq=512, head_size_v=512, ncols1=ncols1, ncols2=ncols2))

for type in TYPES_MMQ:
    with open(f"mmq-instance-{get_short_name(type)}.cu", "w") as f:
        f.write(SOURCE_MMQ.format(type=type))

for type in range(1, 17):
    with open(f"mmf-instance-ncols_{type}.cu", "w") as f:
        f.write(SOURCE_MMF.format(type=type))

for stem, type_k, type_v, head_sizes in TURBO_VARIANTS:
    for dkq, dv in head_sizes:
        for ncols1, ncols2 in TURBO_DECODE_SHAPES:
            with open(f"{stem}-instance-dkq{dkq}-ncols1_{ncols1}-ncols2_{ncols2}.cu", "w") as f:
                f.write(SOURCE_FATTN_MMA_TURBO_START.format(
                    comment=get_turbo_comment(stem, type_k, type_v)))
                f.write(SOURCE_FATTN_MMA_TURBO_CASE.format(
                    dkq=dkq, dv=dv, ncols1=ncols1, ncols2=ncols2, type_k=type_k, type_v=type_v))
