#!/usr/bin/env python3
"""Generate the deterministic pager-corpus-v2 artifact outside the repository."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parent))
from pager_benchmark_contract import CORPUS_SCHEMA, PARTITIONS, case_hash, corpus_hash, validate_corpus


CASES = (
    ("warm-focus", "warm_focus", "Explain the pinned system constraint.", "system anchor: answer only from the supplied context.", 0),
    ("cold-early", "cold_needle", "What is the early retrieval code?", "early-needle-17", 3),
    ("cold-middle", "cold_needle", "What is the middle retrieval code?", "middle-needle-29", 11),
    ("cold-end", "cold_needle", "What is the end retrieval code?", "end-needle-41", 19),
    ("competing-a", "competing_facts", "Which candidate is marked canonical?", "candidate-a", 7),
    ("competing-b", "competing_facts", "Which candidate is marked canonical?", "candidate-b", 13),
    ("tool-anchor", "tool_anchor", "Name the configured tool timeout.", "timeout=30s", 2),
    ("repo-fact", "repository_fact", "Which file owns the page ledger?", "src/llama-cache-budget.cpp", 9),
    ("conversation", "conversation_referent", "What did the user ask to preserve?", "the restoration procedure", 15),
    ("focus-shift", "focus_shift", "After changing topic, what was the original topic?", "page residency", 21),
    ("churn", "adversarial_churn", "Ignore repeated decoys. What is the stable token?", "stable-token-53", 17),
    ("recent-control", "recent_only", "What is the last local instruction?", "use temperature zero", 0),
)


def build_case(index: int, spec: tuple[str, str, str, str, int], partition: str, model: str, tokenizer: str) -> dict[str, object]:
    ident, category, question, answer, distance = spec
    # The partition marker is part of the prompt to prevent calibration/held-out
    # answer leakage while keeping construction fully reproducible.
    prompt = f"pager-corpus-v2/{partition}/{ident}\nContext contains sealed pages.\nQuestion: {question}"
    case: dict[str, object] = {
        "id": ident,
        "partition": partition,
        "category": category,
        "input_construction": "fixed UTF-8 header + category fixture + question; no live retrieval",
        "prompt": prompt,
        "model_sha256": model,
        "tokenizer_sha256": tokenizer,
        "expected_answer": answer if partition == "calibration" else f"{answer} (held-out)",
        "checker": {"type": "exact", "case_sensitive": True, "normalize_whitespace": True},
        "score_rule": "exact normalized answer / 1.0",
        "minimum_score": 1.0,
        "context_tokens": 4096 + index * 1024,
        "page_distance": {"unit": "logical_pages", "from_recent": distance},
        "stable_hash": "",
    }
    case["stable_hash"] = case_hash(case)
    return case


def build_corpus(model: str, tokenizer: str) -> dict[str, object]:
    cases = []
    for index, spec in enumerate(CASES):
        for partition in PARTITIONS:
            # Held-out prompts are distinct, while categories and distance
            # coverage are balanced deterministically.
            cases.append(build_case(index * 2 + (partition == "held_out"), spec, partition, model, tokenizer))
    corpus = {
        "schema": CORPUS_SCHEMA,
        "version": 2,
        "partitions": list(PARTITIONS),
        "model_sha256": model,
        "tokenizer_sha256": tokenizer,
        "construction": "static category fixtures; generated by generate-pager-corpus.py",
        "cases": cases,
    }
    corpus["corpus_hash"] = corpus_hash(cases)
    return corpus


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("output", type=Path)
    parser.add_argument("--model", default="0" * 64, help="model GGUF SHA256")
    parser.add_argument("--tokenizer", default="1" * 64, help="tokenizer/model tokenizer SHA256")
    args = parser.parse_args()
    corpus = build_corpus(args.model, args.tokenizer)
    errors = validate_corpus(corpus)
    if errors:
        parser.error("generated invalid corpus: " + "; ".join(errors))
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(corpus, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(json.dumps({"path": str(args.output), "corpus_hash": corpus["corpus_hash"], "cases": len(corpus["cases"])}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
